"""add invitations

Revision ID: 1e44c8586d59
Revises: 4bead58c099b
Create Date: 2020-11-29 11:26:13.604823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1e44c8586d59"
down_revision = "4bead58c099b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("invited_by", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("acknowledged", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.alter_column(
        "organization_user",
        "role",
        existing_type=postgresql.ENUM(
            "admin", "guest", "member", "owner", name="organization_user_role_enum"
        ),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'owner'::organization_user_role_enum"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization_user",
        "role",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "admin", "guest", "member", "owner", name="organization_user_role_enum"
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'owner'::organization_user_role_enum"),
    )
    op.drop_table("invitation")
    # ### end Alembic commands ###
