"""Add taxon rank.

Revision ID: db3d4cc66dfb
Revises: 3f7382d59c6f
Create Date: 2020-10-21 09:41:04.728156

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as pg


# revision identifiers, used by Alembic.
revision = "db3d4cc66dfb"
down_revision = "3f7382d59c6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    rank_enum = pg.ENUM(
        "kingdom",
        "phylum",
        "class",
        "order",
        "family",
        "tribe",
        "genus",
        "section",
        "series",
        "species",
        "variety",
        "form",
        name="taxon_rank_enum",
    )
    rank_enum.create(op.get_bind())
    op.alter_column(
        "taxon",
        "rank",
        type_=rank_enum,
        nullable=False,
        postgresql_using="rank::taxon_rank_enum",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("taxon", "rank", type_=sa.String(128), nullable=False)
    op.execute("DROP TYPE taxon_rank_enum")
    # ### end Alembic commands ###
